services:
  agent-app:
    container_name: synergies_ai_agent
    image: synergies_ai
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    volumes:
      - .:/code
    working_dir: /code
    command: uv run python /code/main.py
